name: build-pack

on: 
  push:
    branches:
    - main
  schedule:
    - cron: "28 4 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download RSSPAPER
      run: |
        sudo apt install wget
        wget https://github.com/tanrax/RSSPAPER/releases/download/v1.2.0/rsspaper-1.2.0-standalone.jar
    - name: Build
      run: |
        java -jar rsspaper-1.2.0-standalone.jar
    - name: Upload new dist
      run: |
        rm -rf docs/index.html docs/static last_build
        mv dist/index.html docs
        mv dist/static docs/
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        echo "$(date +"%F")" > last_build
        git add docs/index.html
        git add docs/static/
        git add last_build
        git commit -m "$(date +"%F")"
        git push -f origin main

